
<!-- This is the project specific website template -->
<!-- It can be changed as liked or replaced by other content -->

<?php

$domain=ereg_replace('[^\.]*\.(.*)$','\1',$_SERVER['HTTP_HOST']);
$group_name=ereg_replace('([^\.]*)\..*$','\1',$_SERVER['HTTP_HOST']);
$themeroot='http://r-forge.r-project.org/themes/rforge/';

echo '<?xml version="1.0" encoding="UTF-8"?>';
?>
<!DOCTYPE html
	PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en   ">

  <head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $group_name; ?></title>
	<link href="<?php echo $themeroot; ?>styles/estilo1.css" rel="stylesheet" type="text/css" />
  </head>

<body>

<!-- R-Forge Logo -->
<table border="0" width="100%" cellspacing="0" cellpadding="0">
<tr><td>
<a href="/"><img src="<?php echo $themeroot; ?>/images/logo.png" border="0" alt="R-Forge Logo" /> </a> </td> </tr>
</table>


<!-- get project title  -->
<!-- own website starts here, the following may be changed as you like -->

<?php if ($handle=fopen('http://'.$domain.'/export/projtitl.php?group_name='.$group_name,'r')){
$contents = '';
while (!feof($handle)) {
	$contents .= fread($handle, 8192);
}
fclose($handle);
echo $contents; } ?>

<!-- end of project description -->
<pre class="textmate-source"><span class="source source_r">ls(<span class="variable variable_other variable_other_r">package</span><span class="keyword keyword_other keyword_other_r">:</span><span class="variable variable_other variable_other_r">ggextra</span>)
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>area<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>                   <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>arrange<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>                <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>chooseCol<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>colorStrip<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>createCol<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>dichromat.maxcolors<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>   
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>dichromat.names<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>        <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>dichromat.pal<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>          <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>dichromat.types<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>        <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ellipseGrob<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>fieldGrob<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>fielduvGrob<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>           
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>geom_ellipse<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>           <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>geom_field<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>geom_fielduv<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>           <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>geom_ngon<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>geom_star<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomCustom<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomEllipse<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomField<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomFielduv<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomNgon<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>               <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>GeomStar<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>               <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ngonGrob<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>              
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>polygon.regular<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>        <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_abscissa<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>         <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_alpha_manual<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>     <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_angle<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_angle_discrete<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>   <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_angle_manual<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>    
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_ar<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>               <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_ar_discrete<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>      <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_ar_manual<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>        <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_colour_dichromat<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span> <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_fill_dichromat<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>   <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_length<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>          
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_length_manual<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>    <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_ordinate<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>         <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_sides<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>scale_sides_manual<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>     <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleAbscissa<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>          <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleAngle<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleAngleDiscrete<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>     <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleAr<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>                <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleArDiscrete<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>        <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleDichromat<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>         <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleLength<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleLengthDiscrete<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>   
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleOrdinate<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>          <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>ScaleSides<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>star<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>                   <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>starGrob<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>               <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_bb<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>               <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_bw2<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             
 <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_dark<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_flashy<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>           <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_gray2<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>            <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_minimal<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>          <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>theme_talk<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span>             <span class="string string_quoted string_quoted_double string_quoted_double_r"><span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_begin punctuation_definition_string_begin_r">"</span>vp.layout<span class="punctuation punctuation_definition punctuation_definition_string punctuation_definition_string_end punctuation_definition_string_end_r">"</span></span></span></pre>
<p> <img src="plots.png" width=400></p>

<p> <img src="plots-geoms.png" width=400></p>

<p> The <strong>project summary page</strong> you can find <a href="http://<?php echo $domain; ?>/projects/<?php echo $group_name; ?>/"><strong>here</strong></a>. </p>

</body>
</html>
